// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pei223/hook-scheduler/internal/usecase (interfaces: HookScheduleServiceIF)

// Package mock_usecase is a generated GoMock package.
package mock_usecase

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	hookschedule "github.com/pei223/hook-scheduler/internal/domain/hookschedule"
	models "github.com/pei223/hook-scheduler/internal/models"
	types "github.com/pei223/hook-scheduler/pkg/types"
)

// MockHookScheduleServiceIF is a mock of HookScheduleServiceIF interface.
type MockHookScheduleServiceIF struct {
	ctrl     *gomock.Controller
	recorder *MockHookScheduleServiceIFMockRecorder
}

// MockHookScheduleServiceIFMockRecorder is the mock recorder for MockHookScheduleServiceIF.
type MockHookScheduleServiceIFMockRecorder struct {
	mock *MockHookScheduleServiceIF
}

// NewMockHookScheduleServiceIF creates a new mock instance.
func NewMockHookScheduleServiceIF(ctrl *gomock.Controller) *MockHookScheduleServiceIF {
	mock := &MockHookScheduleServiceIF{ctrl: ctrl}
	mock.recorder = &MockHookScheduleServiceIFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookScheduleServiceIF) EXPECT() *MockHookScheduleServiceIFMockRecorder {
	return m.recorder
}

// CreateHookSchedule mocks base method.
func (m *MockHookScheduleServiceIF) CreateHookSchedule(arg0 context.Context, arg1 *hookschedule.HookScheduleCreateParams) (*models.HookSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHookSchedule", arg0, arg1)
	ret0, _ := ret[0].(*models.HookSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHookSchedule indicates an expected call of CreateHookSchedule.
func (mr *MockHookScheduleServiceIFMockRecorder) CreateHookSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHookSchedule", reflect.TypeOf((*MockHookScheduleServiceIF)(nil).CreateHookSchedule), arg0, arg1)
}

// DeleteHookSchedule mocks base method.
func (m *MockHookScheduleServiceIF) DeleteHookSchedule(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHookSchedule", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHookSchedule indicates an expected call of DeleteHookSchedule.
func (mr *MockHookScheduleServiceIFMockRecorder) DeleteHookSchedule(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHookSchedule", reflect.TypeOf((*MockHookScheduleServiceIF)(nil).DeleteHookSchedule), arg0, arg1)
}

// GetHookSchedule mocks base method.
func (m *MockHookScheduleServiceIF) GetHookSchedule(arg0 context.Context, arg1 uuid.UUID, arg2 bool) (*models.HookSchedule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHookSchedule", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.HookSchedule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHookSchedule indicates an expected call of GetHookSchedule.
func (mr *MockHookScheduleServiceIFMockRecorder) GetHookSchedule(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHookSchedule", reflect.TypeOf((*MockHookScheduleServiceIF)(nil).GetHookSchedule), arg0, arg1, arg2)
}

// ListHookSchedules mocks base method.
func (m *MockHookScheduleServiceIF) ListHookSchedules(arg0 context.Context, arg1 *types.ListParams, arg2 bool) (models.HookScheduleSlice, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListHookSchedules", arg0, arg1, arg2)
	ret0, _ := ret[0].(models.HookScheduleSlice)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListHookSchedules indicates an expected call of ListHookSchedules.
func (mr *MockHookScheduleServiceIFMockRecorder) ListHookSchedules(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListHookSchedules", reflect.TypeOf((*MockHookScheduleServiceIF)(nil).ListHookSchedules), arg0, arg1, arg2)
}
