// Code generated by SQLBoiler 4.17.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	HookHistories string
	HookSchedules string
	Hooks         string
}{
	HookHistories: "hook_histories",
	HookSchedules: "hook_schedules",
	Hooks:         "hooks",
}
