// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/pei223/hook-scheduler/internal/domain/hook (interfaces: HookRepo)

// Package mock_hook is a generated GoMock package.
package mock_hook

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	hook "github.com/pei223/hook-scheduler/internal/domain/hook"
	models "github.com/pei223/hook-scheduler/internal/models"
)

// MockHookRepo is a mock of HookRepo interface.
type MockHookRepo struct {
	ctrl     *gomock.Controller
	recorder *MockHookRepoMockRecorder
}

// MockHookRepoMockRecorder is the mock recorder for MockHookRepo.
type MockHookRepoMockRecorder struct {
	mock *MockHookRepo
}

// NewMockHookRepo creates a new mock instance.
func NewMockHookRepo(ctrl *gomock.Controller) *MockHookRepo {
	mock := &MockHookRepo{ctrl: ctrl}
	mock.recorder = &MockHookRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHookRepo) EXPECT() *MockHookRepoMockRecorder {
	return m.recorder
}

// CreateHook mocks base method.
func (m *MockHookRepo) CreateHook(arg0 context.Context, arg1 *sql.Tx, arg2 *hook.HookCreateParams) (*models.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateHook indicates an expected call of CreateHook.
func (mr *MockHookRepoMockRecorder) CreateHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateHook", reflect.TypeOf((*MockHookRepo)(nil).CreateHook), arg0, arg1, arg2)
}

// DeleteHook mocks base method.
func (m *MockHookRepo) DeleteHook(arg0 context.Context, arg1 *sql.Tx, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteHook indicates an expected call of DeleteHook.
func (mr *MockHookRepoMockRecorder) DeleteHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteHook", reflect.TypeOf((*MockHookRepo)(nil).DeleteHook), arg0, arg1, arg2)
}

// GetAllHooks mocks base method.
func (m *MockHookRepo) GetAllHooks(arg0 context.Context, arg1 *sql.Tx, arg2, arg3 int) (models.HookSlice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllHooks", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(models.HookSlice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllHooks indicates an expected call of GetAllHooks.
func (mr *MockHookRepoMockRecorder) GetAllHooks(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllHooks", reflect.TypeOf((*MockHookRepo)(nil).GetAllHooks), arg0, arg1, arg2, arg3)
}

// GetHook mocks base method.
func (m *MockHookRepo) GetHook(arg0 context.Context, arg1 *sql.Tx, arg2 uuid.UUID) (*models.Hook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHook", arg0, arg1, arg2)
	ret0, _ := ret[0].(*models.Hook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHook indicates an expected call of GetHook.
func (mr *MockHookRepoMockRecorder) GetHook(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHook", reflect.TypeOf((*MockHookRepo)(nil).GetHook), arg0, arg1, arg2)
}
